name: Main

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: get ver
        run: |
          echo "$(cat xray.sh | grep ver=)" >> $GITHUB_ENV
          echo "old=$(git tag | tail -n1)" >> $GITHUB_ENV
      - name: test
        run: |
          bash -n install.sh xray.sh src/*.sh tests/*.sh
          bash tests/test_network.sh
      - name: zip
        run: |
          zip -9vr code.zip . -x .\*
          sha256sum code.zip > code.zip.sha256
      - name: release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            code.zip
            code.zip.sha256
          tag_name: ${{ env.is_sh_ver }}
